import Vue from 'vue';
import Router from 'vue-router';
Vue.use(Router);
let router = new Router({
    mode: 'history',
    routes:[{
        path: '/login',
        name: 'login',
        component:()=>
            import('./components/basic/loginAdmin')
    },
    {
        path:'/',
        name:'landingpage',
        component:()=>
            import('./components/basic/landingPage')
    },
    {
        path:'/navigation',
        name:'navigationPage',
        component:()=>
            import('./components/basic/navigationPage')
    },
    {
        path:'/500error',
        props:true,
        component:()=>
            import('./components/sample/500Page'),

    },
    {
        path:'/404error',
        props:true,
        component:()=>
            import('./components/sample/404Page'),
            
    },
    {
        path:'/admin',
        name:'admin',
        component:()=>
            import('./components/admin/adminBase'),
        children:[
            {
                path:'/admindash',
                props:true,
                component:()=>
                    import('./components/admin/dashBoard')
            },
            {
                path:'/appointment',
                props:true,
                component:()=>
                    import('./components/admin/appointmentVisitor')
            },
            {
                path:'/adminprofile',
                props:true,
                component:()=>
                    import('./components/admin/profileAdmin')
            },
            {
                path:'/loguser',
                props:true,
                component:()=>
                    import('./components/admin/logUser')
            },
        ]
    },
    {
        path:'/superadmin',
        name:'superadmin',
        component:()=>
            import('./components/superadmin/adminPanel'),
        children:[
            {
                path: '/dashboard',
                props:true,
                component:()=>
                    import('./components/superadmin/dashBoard'),
            },
            {
                path:'/profilesuper',
                props:true,
                component:()=>
                    import('./components/superadmin/profileSuper'),
            },
            {
                path:'/securitymanagement',
                props:true,
                component:()=>
                    import('./components/superadmin/securityPage'),
            },
            {
                path:'/securityregistration',
                props:true,
                component:()=>
                    import('./components/superadmin/securityRegistration')
            },
            {
                path:'/TestPage',
                props:true,
                component:()=>
                    import('./components/superadmin/TestPage')
            },
            
            {
                path:'/updatepassword',
                props:true,
                component:()=>
                    import('./components/superadmin/updatePassword')
            },
            {
                path:'/securitylist',
                props:true,
                component:()=>
                    import('./components/superadmin/securityList')
            },
            {
                path:'/securityprofile',
                props:true,
                component:()=>
                    import('./components/superadmin/securityProfile')
            },
            {
                path:'/securityupdate',
                props:true,
                component:()=>
                    import('./components/superadmin/securityUpdate')
            },
            {
                path:'/addadmin',
                props:true,
                component:()=>
                    import('./components/superadmin/addAdmin')
            },
            {
                path:'/addlocation',
                props:true,
                component:()=>
                    import('./components/superadmin/addLocation')
            },
            {
                path:'/viewallocation',
                props:true,
                component:()=>
                    import('./components/superadmin/viewAllocation')
            },
            {
                path:'/userlog',
                props:true,
                component:()=>
                    import('./components/superadmin/userLog')
            },
            {
                path:'/roughwork',
                props:true,
                component:()=>
                    import('./components/sample/roughWork')
            },
            {
                path:'/securityedit',
                props:true,
                component:()=>
                    import('./components/superadmin/securityEdit')
            },
            {
                path:'/securityallocation',
                props:true,
                component:()=>
                    import('./components/superadmin/securityAllocation')
            },
            {
                path:'/completed',
                props:true,
                component:()=>
                    import('./components/sample/comPleted')
            },
            

        ]
    }
]
})
export default router;